# Generated by Django 5.2.8 on 2026-02-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="subject",
        ),
    ]
