# Generated by Django 5.2.8 on 2026-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_remove_contact_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
